theme: jekyll-theme-cayman

title: Kakoune Community Articles
description: A collection of articles about Kakoune, in multiple languages, written by the community

markdown: kramdown
kramdown:
    input: GFM

plugins:
    - jekyll-feed

github:
    - is_project_page: false
